### ISSUE TITLE
#include <parallel/algorithm> not found while compiling in visual studio 12

### ISSUE THREAD

**Issue by shalinsirwani** [sallesviana/MeshIntersection#13]

**Comment by sallesviana** [comment]
This is the STL parallel mode (only available in gcc -- https://gcc.gnu.org/onlinedocs/libstdc++/manual/parallel_mode.html). 

You can safely remove this include (and replace "__gnu_parallel::" with "std::" throughout the code). However, this will make the program slower (since STL functions will not run in parallel)
